name: Update Wikidata JSON

on:
  schedule:
    # Weekly cronjob: every Sunday at midnight
    - cron: "0 0 * * 0"
  workflow_dispatch: # Enables manual execution of the workflow via GitHub

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run script to retrieve data
        run: npm run update-data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_FOR_AUTOMERGE }}
          commit-message: "Update data.json"
          title: "Update Wikidata JSON"
          body: "Automated data update via scheduled workflow."
          branch: update-data-json
          base: main
          add-paths: src/data.json
          delete-branch: true
          draft: false
          labels: automated-update
          auto-merge: true
