name: Update Wikidata JSON

on:
  schedule:
    # Wöchentlicher Cronjob: jeden Sonntag um Mitternacht
    - cron: "0 0 * * 0"
  workflow_dispatch: # Ermöglicht das manuelle Ausführen des Workflows über GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # oder eine andere Version

      - name: Install dependencies
        run: npm install

      - name: Run script to fetch data
        run: npm run update-data

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json"
          git push
